"""
=========================================================
JOBURA WEALTH®
NSE Institutional Wealth Management Platform
Institutional Reporting Engine
Version 2.0
=========================================================

Produces professional institutional reports using
outputs generated by:

• simulation.py
• portfolio.py
• analytics.py
• risk.py
• ai.py
• retirement.py

This module performs NO financial calculations.
It only formats and organizes results.
=========================================================
"""

# ==========================================================
# IMPORTS
# ==========================================================

from datetime import datetime
import base64
import io

import matplotlib.pyplot as plt
import numpy as np

# ==========================================================
# REPORT INFORMATION
# ==========================================================

PLATFORM_NAME = "JOBURA WEALTH®"

SYSTEM_NAME = (
    "NSE Institutional Wealth Management Platform"
)

REPORT_VERSION = "2.0"

REPORT_EDITION = (
    "Professional Institutional Analytics Suite"
)

COPYRIGHT = (
    "© 2026 Jobura Solutions. All Rights Reserved."
)

DEFAULT_CURRENCY = "KES"

# ==========================================================
# REPORT METADATA
# ==========================================================

def report_metadata():

    """
    Generates report metadata.
    """

    return {

        "platform": PLATFORM_NAME,

        "system": SYSTEM_NAME,

        "version": REPORT_VERSION,

        "edition": REPORT_EDITION,

        "generated":

            datetime.now().strftime(
                "%d %B %Y %H:%M"
            ),

        "currency":

            DEFAULT_CURRENCY,

        "copyright":

            COPYRIGHT

    }


# ==========================================================
# CURRENCY FORMATTER
# ==========================================================

def money(value):

    """
    Formats values as Kenyan Shillings.
    """

    try:

        return f"{DEFAULT_CURRENCY} {float(value):,.2f}"

    except Exception:

        return f"{DEFAULT_CURRENCY} 0.00"


# ==========================================================
# PERCENTAGE FORMATTER
# ==========================================================

def percent(value):

    """
    Formats percentage values.
    """

    try:

        return f"{float(value):.2f}%"

    except Exception:

        return "0.00%"


# ==========================================================
# NUMBER FORMATTER
# ==========================================================

def number(value, decimals=2):

    """
    Generic numeric formatter.
    """

    try:

        return round(float(value), decimals)

    except Exception:

        return 0.0


# ==========================================================
# DATE FORMATTER
# ==========================================================

def report_date():

    """
    Returns today's report date.
    """

    return datetime.now().strftime(
        "%d %B %Y"
    )


# ==========================================================
# REPORT TITLE
# ==========================================================

def report_title(model, mode):

    """
    Generates the report title.
    """

    return (

        f"{PLATFORM_NAME}\n"

        f"{model.title()} Portfolio "

        f"({mode.title()} Market)"

    )


# ==========================================================
# REPORT FOOTER
# ==========================================================

def report_footer():

    """
    Footer shown on exported reports.
    """

    return {

        "prepared_by":

            PLATFORM_NAME,

        "edition":

            REPORT_EDITION,

        "version":

            REPORT_VERSION,

        "copyright":

            COPYRIGHT

    }
# ==========================================================
# EXECUTIVE SUMMARY
# ==========================================================

def executive_summary(
    summary,
    analytics,
    risk,
    ai
):
    """
    Builds the executive investment summary.
    """

    return {

        "capital_invested":
            money(summary.get(
                "invested",
                0
            )),

        "portfolio_value":
            money(summary.get(
                "value",
                0
            )),

        "capital_gain":
            money(summary.get(
                "profit",
                0
            )),

        "dividend_income":
            money(summary.get(
                "dividend_income",
                0
            )),

        "roi":
            percent(summary.get(
                "roi",
                0
            )),

        "cagr":
            percent(analytics.get(
                "cagr",
                0
            )),

        "institutional_rating":
            risk.get(
                "institutional_rating",
                "N/A"
            ),

        "risk_classification":
            risk.get(
                "classification",
                "Unknown"
            ),

        "health_score":
            ai.get(
                "health",
                0
            ),

        "generated":
            report_date()

    }


# ==========================================================
# INVESTMENT SNAPSHOT
# ==========================================================

def investment_snapshot(
    summary
):
    """
    Quick portfolio statistics.
    """

    return {

        "investment":
            money(
                summary.get(
                    "invested",
                    0
                )
            ),

        "portfolio":
            money(
                summary.get(
                    "value",
                    0
                )
            ),

        "profit":
            money(
                summary.get(
                    "profit",
                    0
                )
            ),

        "roi":
            percent(
                summary.get(
                    "roi",
                    0
                )
            )

    }


# ==========================================================
# PERFORMANCE SNAPSHOT
# ==========================================================

def performance_snapshot(
    analytics
):
    """
    Performance overview.
    """

    return {

        "annual_return":
            percent(
                analytics.get(
                    "annual_return",
                    0
                )
            ),

        "cagr":
            percent(
                analytics.get(
                    "cagr",
                    0
                )
            ),

        "dividend_yield":
            percent(
                analytics.get(
                    "dividend_yield",
                    0
                )
            ),

        "portfolio_health":
            analytics.get(
                "health_score",
                0
            ),

        "quality_score":
            analytics.get(
                "quality_score",
                0
            )

    }


# ==========================================================
# INSTITUTIONAL OVERVIEW
# ==========================================================

def institutional_overview(
    risk,
    ai
):
    """
    Institutional portfolio assessment.
    """

    return {

        "institutional_rating":
            risk.get(
                "institutional_rating",
                "N/A"
            ),

        "risk_score":
            risk.get(
                "risk_score",
                0
            ),

        "risk":
            risk.get(
                "classification",
                "Unknown"
            ),

        "portfolio_health":
            ai.get(
                "health",
                0
            ),

        "diversification":
            ai.get(
                "diversification",
                0
            ),

        "ai_commentary":
            ai.get(
                "message",
                ""
            )

    }


# ==========================================================
# EXECUTIVE HIGHLIGHTS
# ==========================================================

def executive_highlights(
    summary,
    analytics,
    risk,
    ai
):
    """
    High-level investment highlights.
    """

    return [

        f"Portfolio Value: {money(summary.get('value', 0))}",

        f"Overall ROI: {percent(summary.get('roi', 0))}",

        f"Institutional Rating: {risk.get('institutional_rating', 'N/A')}",

        f"Risk Classification: {risk.get('classification', 'Unknown')}",

        f"Portfolio Health: {ai.get('health', 0):.1f}/100",

        f"Dividend Yield: {percent(analytics.get('dividend_yield', 0))}"

    ]
# ==========================================================
# PORTFOLIO ALLOCATION TABLE
# ==========================================================

def allocation_table(portfolio):
    """
    Portfolio allocation summary.
    """

    rows = []

    for asset in portfolio:

        rows.append({

            "company":
                asset.get("asset", ""),

            "code":
                asset.get("code", ""),

            "sector":
                asset.get("sector", ""),

            "allocation":
                percent(
                    asset.get(
                        "allocation_pct",
                        0
                    )
                ),

            "capital":
                money(
                    asset.get(
                        "capital",
                        0
                    )
                )

        })

    return rows


# ==========================================================
# COMPANY PERFORMANCE TABLE
# ==========================================================

def company_performance(portfolio):
    """
    Institutional company performance report.
    """

    rows = []

    for asset in portfolio:

        rows.append({

            "company":
                asset.get("asset", ""),

            "sector":
                asset.get("sector", ""),

            "current_value":
                money(
                    asset.get(
                        "current_value",
                        0
                    )
                ),

            "capital_gain":
                money(
                    asset.get(
                        "capital_gain",
                        0
                    )
                ),

            "dividends":
                money(
                    asset.get(
                        "dividends",
                        0
                    )
                ),

            "total_return":
                money(
                    asset.get(
                        "total_return",
                        0
                    )
                ),

            "annual_return":
                percent(
                    asset.get(
                        "annual_return",
                        0
                    )
                )

        })

    return rows


# ==========================================================
# SECTOR BREAKDOWN
# ==========================================================

def sector_breakdown(portfolio):
    """
    Portfolio allocation by sector.
    """

    sectors = {}

    for asset in portfolio:

        sector = asset.get(
            "sector",
            "Unknown"
        )

        allocation = asset.get(
            "allocation_pct",
            0
        )

        sectors[sector] = (
            sectors.get(sector, 0)
            + allocation
        )

    rows = []

    for sector, allocation in sectors.items():

        rows.append({

            "sector": sector,

            "allocation":
                percent(allocation)

        })

    return rows


# ==========================================================
# DIVIDEND REPORT
# ==========================================================

def dividend_report(portfolio):
    """
    Dividend income by company.
    """

    rows = []

    total = 0

    for asset in portfolio:

        dividend = asset.get(
            "dividends",
            0
        )

        total += dividend

        rows.append({

            "company":
                asset.get("asset", ""),

            "dividend":
                money(dividend),

            "yield":
                percent(
                    asset.get(
                        "dividend_yield",
                        0
                    )
                )

        })

    return {

        "companies": rows,

        "total_dividends":
            money(total)

    }


# ==========================================================
# ASSET STATISTICS
# ==========================================================

def asset_statistics(portfolio):
    """
    Portfolio statistics.
    """

    if not portfolio:

        return {}

    total_assets = len(portfolio)

    total_value = sum(

        asset.get(
            "current_value",
            0
        )

        for asset in portfolio

    )

    total_income = sum(

        asset.get(
            "dividends",
            0
        )

        for asset in portfolio

    )

    return {

        "companies":

            total_assets,

        "portfolio_value":

            money(total_value),

        "dividend_income":

            money(total_income),

        "average_value":

            money(
                total_value /
                total_assets
            )

    }


# ==========================================================
# COMPLETE PORTFOLIO REPORT
# ==========================================================

def portfolio_report(portfolio):
    """
    Complete institutional portfolio report.
    """

    return {

        "allocation":

            allocation_table(
                portfolio
            ),

        "performance":

            company_performance(
                portfolio
            ),

        "sector_breakdown":

            sector_breakdown(
                portfolio
            ),

        "dividends":

            dividend_report(
                portfolio
            ),

        "statistics":

            asset_statistics(
                portfolio
            )

    }
# ==========================================================
# PERFORMANCE SUMMARY
# ==========================================================

def performance_summary(analytics):
    """
    Executive performance summary.
    """

    return {

        "roi":
            percent(
                analytics.get(
                    "roi",
                    0
                )
            ),

        "cagr":
            percent(
                analytics.get(
                    "cagr",
                    0
                )
            ),

        "annual_return":
            percent(
                analytics.get(
                    "annual_return",
                    0
                )
            ),

        "portfolio_health":
            analytics.get(
                "health_score",
                0
            ),

        "quality_score":
            analytics.get(
                "quality_score",
                0
            ),

        "diversification":
            analytics.get(
                "diversification",
                0
            )

    }


# ==========================================================
# GROWTH METRICS
# ==========================================================

def growth_metrics(analytics):
    """
    Portfolio growth statistics.
    """

    return {

        "capital_growth":
            money(
                analytics.get(
                    "capital_growth",
                    0
                )
            ),

        "income_growth":
            money(
                analytics.get(
                    "income_growth",
                    0
                )
            ),

        "portfolio_growth":
            percent(
                analytics.get(
                    "portfolio_growth",
                    0
                )
            ),

        "annual_return":
            percent(
                analytics.get(
                    "annual_return",
                    0
                )
            )

    }


# ==========================================================
# DIVIDEND ANALYTICS
# ==========================================================

def dividend_analytics(analytics):
    """
    Dividend performance.
    """

    return {

        "dividend_income":
            money(
                analytics.get(
                    "dividend_income",
                    0
                )
            ),

        "dividend_yield":
            percent(
                analytics.get(
                    "dividend_yield",
                    0
                )
            ),

        "dividend_growth":
            percent(
                analytics.get(
                    "dividend_growth",
                    0
                )
            )

    }


# ==========================================================
# PERFORMANCE RATINGS
# ==========================================================

def performance_ratings(analytics):
    """
    Institutional performance ratings.
    """

    return {

        "health_score":
            analytics.get(
                "health_score",
                0
            ),

        "quality_score":
            analytics.get(
                "quality_score",
                0
            ),

        "stability_score":
            analytics.get(
                "stability_score",
                0
            ),

        "institutional_rating":
            analytics.get(
                "institutional_rating",
                "N/A"
            )

    }


# ==========================================================
# ANALYTICS DASHBOARD
# ==========================================================

def analytics_dashboard(analytics):
    """
    Dashboard-ready analytics.
    """

    return {

        "summary":
            performance_summary(
                analytics
            ),

        "growth":
            growth_metrics(
                analytics
            ),

        "dividends":
            dividend_analytics(
                analytics
            ),

        "ratings":
            performance_ratings(
                analytics
            )

    }


# ==========================================================
# COMPLETE ANALYTICS REPORT
# ==========================================================

def analytics_report(analytics):
    """
    Complete institutional analytics report.
    """

    return {

        "performance":
            performance_summary(
                analytics
            ),

        "growth":
            growth_metrics(
                analytics
            ),

        "dividend":
            dividend_analytics(
                analytics
            ),

        "ratings":
            performance_ratings(
                analytics
            ),

        "dashboard":
            analytics_dashboard(
                analytics
            )

    }
# ==========================================================
# RISK REPORT
# ==========================================================

def risk_report(risk):
    """
    Institutional risk report.
    """

    return {

        "classification":
            risk.get(
                "classification",
                "UNKNOWN"
            ),

        "institutional_rating":
            risk.get(
                "institutional_rating",
                "N/A"
            ),

        "risk_score":
            risk.get(
                "risk_score",
                0
            ),

        "volatility":
            percent(
                risk.get(
                    "volatility",
                    0
                )
            ),

        "sharpe_ratio":
            risk.get(
                "sharpe_ratio",
                0
            ),

        "sortino_ratio":
            risk.get(
                "sortino_ratio",
                0
            ),

        "beta":
            risk.get(
                "beta",
                1.0
            ),

        "maximum_drawdown":
            percent(
                risk.get(
                    "maximum_drawdown",
                    0
                )
            ),

        "value_at_risk":
            percent(
                risk.get(
                    "value_at_risk",
                    0
                )
            ),

        "conditional_value_at_risk":
            percent(
                risk.get(
                    "conditional_value_at_risk",
                    0
                )
            )

    }


# ==========================================================
# STRESS TEST REPORT
# ==========================================================

def stress_test_report(risk):
    """
    Stress testing summary.
    """

    return risk.get(
        "stress_tests",
        {}
    )


# ==========================================================
# AI SUMMARY
# ==========================================================

def ai_summary(ai):
    """
    Institutional AI summary.
    """

    return {

        "health":
            ai.get(
                "health",
                0
            ),

        "rating":
            ai.get(
                "rating",
                "N/A"
            ),

        "risk":
            ai.get(
                "risk",
                "UNKNOWN"
            ),

        "risk_score":
            ai.get(
                "risk_score",
                0
            ),

        "diversification":
            ai.get(
                "diversification",
                0
            ),

        "dividend_score":
            ai.get(
                "dividend_score",
                0
            ),

        "market_mode":
            ai.get(
                "market_mode",
                "Normal"
            ),

        "investment_model":
            ai.get(
                "investment_model",
                "Balanced"
            ),

        "message":
            ai.get(
                "message",
                ""
            )

    }


# ==========================================================
# AI RECOMMENDATIONS
# ==========================================================

def ai_recommendations(ai):
    """
    Company recommendations.
    """

    return ai.get(
        "recommendations",
        []
    )


# ==========================================================
# PORTFOLIO INSIGHTS
# ==========================================================

def portfolio_insights(ai):
    """
    AI portfolio insights.
    """

    return {

        "strengths":
            ai.get(
                "strengths",
                []
            ),

        "weaknesses":
            ai.get(
                "weaknesses",
                []
            ),

        "rebalance":
            ai.get(
                "rebalance",
                []
            ),

        "best_pick":
            ai.get(
                "best_pick",
                {}
            )

    }


# ==========================================================
# EXECUTIVE COMMENTARY
# ==========================================================

def executive_commentary(ai):
    """
    AI executive commentary.
    """

    return {

        "executive_summary":
            ai.get(
                "executive_summary",
                ""
            ),

        "market_outlook":
            ai.get(
                "market_outlook",
                ""
            ),

        "generated":
            ai.get(
                "generated",
                "Institutional AI Engine"
            )

    }


# ==========================================================
# COMPLETE RISK & AI REPORT
# ==========================================================

def risk_ai_report(
    risk,
    ai
):
    """
    Complete institutional
    Risk & AI report.
    """

    return {

        "risk":
            risk_report(
                risk
            ),

        "stress_tests":
            stress_test_report(
                risk
            ),

        "ai":
            ai_summary(
                ai
            ),

        "recommendations":
            ai_recommendations(
                ai
            ),

        "insights":
            portfolio_insights(
                ai
            ),

        "commentary":
            executive_commentary(
                ai
            )

    }
# ==========================================================
# RETIREMENT SUMMARY
# ==========================================================

def retirement_summary(retirement):
    """
    Executive retirement summary.
    """

    return {

        "target":
            money(
                retirement.get(
                    "target",
                    0
                )
            ),

        "projected_portfolio":
            money(
                retirement.get(
                    "portfolio",
                    0
                )
            ),

        "achievement":
            percent(
                retirement.get(
                    "achievement",
                    0
                )
            ),

        "status":
            retirement.get(
                "status",
                "Unknown"
            )

    }


# ==========================================================
# RETIREMENT INCOME
# ==========================================================

def retirement_income(retirement):
    """
    Retirement income analysis.
    """

    return {

        "monthly_income":
            money(
                retirement.get(
                    "monthly_income",
                    0
                )
            ),

        "annual_income":
            money(
                retirement.get(
                    "annual_income",
                    retirement.get(
                        "monthly_income",
                        0
                    ) * 12
                )
            )

    }


# ==========================================================
# SAVINGS PLAN
# ==========================================================

def savings_plan(retirement):
    """
    Retirement savings requirements.
    """

    return {

        "required_monthly":
            money(
                retirement.get(
                    "required_monthly",
                    0
                )
            ),

        "required_annual":
            money(
                retirement.get(
                    "required_annual",
                    retirement.get(
                        "required_monthly",
                        0
                    ) * 12
                )
            )

    }


# ==========================================================
# GOAL TRACKING
# ==========================================================

def goal_tracking(retirement):
    """
    Retirement goal tracking.
    """

    return {

        "achievement":
            percent(
                retirement.get(
                    "achievement",
                    0
                )
            ),

        "remaining_gap":
            money(
                retirement.get(
                    "remaining_gap",
                    0
                )
            ),

        "years_remaining":
            retirement.get(
                "years_remaining",
                0
            )

    }


# ==========================================================
# WEALTH PLANNING
# ==========================================================

def wealth_planning(retirement):
    """
    Long-term wealth planning.
    """

    return {

        "wealth_target":
            money(
                retirement.get(
                    "target",
                    0
                )
            ),

        "projected_wealth":
            money(
                retirement.get(
                    "portfolio",
                    0
                )
            ),

        "wealth_gap":
            money(
                retirement.get(
                    "remaining_gap",
                    0
                )
            )

    }


# ==========================================================
# COMPLETE RETIREMENT REPORT
# ==========================================================

def retirement_report(retirement):
    """
    Complete retirement &
    wealth planning report.
    """

    return {

        "summary":
            retirement_summary(
                retirement
            ),

        "income":
            retirement_income(
                retirement
            ),

        "savings":
            savings_plan(
                retirement
            ),

        "goal_tracking":
            goal_tracking(
                retirement
            ),

        "wealth_planning":
            wealth_planning(
                retirement
            )

    }
# ==========================================================
# PORTFOLIO GROWTH CHART
# ==========================================================

def chart(curve):
    """
    Portfolio growth chart.
    Returns a base64 PNG image.
    """

    fig, ax = plt.subplots(figsize=(10, 5))

    fig.patch.set_facecolor("#0b0f19")
    ax.set_facecolor("#0b0f19")

    x = np.arange(len(curve))
    y = np.array(curve)

    ax.plot(
        x,
        y,
        linewidth=2,
        color="#60a5fa"
    )

    ax.fill_between(
        x,
        y,
        alpha=0.20,
        color="#60a5fa"
    )

    ax.set_title(
        "Portfolio Growth",
        color="white",
        fontsize=14
    )

    ax.set_xlabel(
        "Months",
        color="white"
    )

    ax.set_ylabel(
        "Portfolio Value (KES)",
        color="white"
    )

    ax.grid(
        alpha=0.25
    )

    ax.tick_params(colors="white")

    ax.spines["bottom"].set_color("#334155")
    ax.spines["left"].set_color("#334155")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    buf = io.BytesIO()

    fig.savefig(
        buf,
        format="png",
        dpi=120,
        bbox_inches="tight"
    )

    plt.close(fig)

    buf.seek(0)

    return base64.b64encode(
        buf.read()
    ).decode()


# ==========================================================
# ALLOCATION PIE CHART
# ==========================================================

def allocation_chart(portfolio):
    """
    Portfolio allocation pie chart.
    """

    labels = [
        p["asset"]
        for p in portfolio
    ]

    sizes = [
        p["allocation_pct"]
        for p in portfolio
    ]

    fig, ax = plt.subplots(figsize=(7,7))

    ax.pie(

        sizes,

        labels=labels,

        autopct="%1.1f%%",

        startangle=90

    )

    ax.set_title(
        "Portfolio Allocation"
    )

    buf = io.BytesIO()

    fig.savefig(
        buf,
        format="png",
        bbox_inches="tight"
    )

    plt.close(fig)

    buf.seek(0)

    return base64.b64encode(
        buf.read()
    ).decode()


# ==========================================================
# SECTOR ALLOCATION CHART
# ==========================================================

def sector_chart(portfolio):
    """
    Sector allocation chart.
    """

    sectors = {}

    for asset in portfolio:

        sector = asset.get(
            "sector",
            "Unknown"
        )

        sectors[sector] = (

            sectors.get(
                sector,
                0
            )

            +

            asset.get(
                "allocation_pct",
                0
            )

        )

    labels = list(
        sectors.keys()
    )

    values = list(
        sectors.values()
    )

    fig, ax = plt.subplots(
        figsize=(8,5)
    )

    ax.bar(
        labels,
        values
    )

    ax.set_ylabel(
        "Allocation (%)"
    )

    ax.set_title(
        "Sector Allocation"
    )

    plt.xticks(
        rotation=25
    )

    buf = io.BytesIO()

    fig.savefig(
        buf,
        format="png",
        bbox_inches="tight"
    )

    plt.close(fig)

    buf.seek(0)

    return base64.b64encode(
        buf.read()
    ).decode()


# ==========================================================
# RISK DASHBOARD CHART
# ==========================================================

def risk_chart(risk):
    """
    Risk indicator chart.
    """

    labels = [

        "Risk",

        "Health",

        "Diversification"

    ]

    values = [

        risk.get(
            "risk_score",
            0
        ),

        risk.get(
            "health_score",
            0
        ),

        risk.get(
            "diversification",
            0
        )

    ]

    fig, ax = plt.subplots(
        figsize=(7,5)
    )

    ax.bar(
        labels,
        values
    )

    ax.set_ylim(
        0,
        100
    )

    ax.set_title(
        "Institutional Risk Dashboard"
    )

    buf = io.BytesIO()

    fig.savefig(
        buf,
        format="png",
        bbox_inches="tight"
    )

    plt.close(fig)

    buf.seek(0)

    return base64.b64encode(
        buf.read()
    ).decode()


# ==========================================================
# COMPLETE CHART SUITE
# ==========================================================

def charts(
    curve,
    portfolio,
    risk
):
    """
    Generates all charts
    used by the platform.
    """

    return {

        "growth":

            chart(
                curve
            ),

        "allocation":

            allocation_chart(
                portfolio
            ),

        "sector":

            sector_chart(
                portfolio
            ),

        "risk":

            risk_chart(
                risk
            )

    }
# ==========================================================
# MASTER INSTITUTIONAL REPORT
# ==========================================================

def generate_report(
    summary,
    portfolio,
    analytics,
    risk,
    ai,
    retirement,
    curve,
    model,
    mode
):
    """
    =======================================================
    JOBURA WEALTH®
    Institutional Master Reporting Engine

    Combines all reporting modules into one
    professional institutional report.

    No calculations are performed here.

    Inputs are generated by:

        simulation.py
        portfolio.py
        analytics.py
        risk.py
        ai.py
        retirement.py

    =======================================================
    """

    report = {

        # --------------------------------------------------
        # Metadata
        # --------------------------------------------------
        "metadata":

            report_metadata(),

        # --------------------------------------------------
        # Cover
        # --------------------------------------------------
        "title":

            report_title(
                model,
                mode
            ),

        # --------------------------------------------------
        # Executive Summary
        # --------------------------------------------------
        "executive":

            executive_summary(
                summary,
                analytics,
                risk,
                ai
            ),

        "highlights":

            executive_highlights(
                summary,
                analytics,
                risk,
                ai
            ),

        "investment_snapshot":

            investment_snapshot(
                summary
            ),

        "institutional_overview":

            institutional_overview(
                risk,
                ai
            ),

        # --------------------------------------------------
        # Portfolio
        # --------------------------------------------------
        "portfolio":

            portfolio_report(
                portfolio
            ),

        # --------------------------------------------------
        # Analytics
        # --------------------------------------------------
        "analytics":

            analytics_report(
                analytics
            ),

        # --------------------------------------------------
        # Risk & AI
        # --------------------------------------------------
        "risk_ai":

            risk_ai_report(
                risk,
                ai
            ),

        # --------------------------------------------------
        # Retirement
        # --------------------------------------------------
        "retirement":

            retirement_report(
                retirement
            ),

        # --------------------------------------------------
        # Charts
        # --------------------------------------------------
        "charts":

            charts(
                curve,
                portfolio,
                risk
            ),
        # --------------------------------------------------
        # Footer
        # --------------------------------------------------
        "footer":

            report_footer()

    }

    return report
